export interface ProductReview {
  author: string;
  rating: number;
  text: string;
  date?: string;
  country?: string;
  highlight?: string;
}

/**
 * Interface representing the product details scraped from AliExpress.
 */
export interface ScrapedProduct {
  productId: string;
  title: string;
  description: string;
  price: string;
  imageUrls: string[];
  reviews: ProductReview[];
  sourceUrl: string;
}

/**
 * Interface representing marketing copy and target audience generated by Google Gemini.
 */
export interface MarketingData {
  facebookAdCopies: string[];
  targetAudience: string[];
  keywords: string[];
  customerReviews?: ProductReview[];
  imagePrompts?: string[];
}

/**
 * Interface representing local file paths and browser-accessible URLs for media assets.
 */
export interface MediaAssets {
  images: string[];
  videoUrl: string;
  localImagePaths: string[];
  localVideoPath: string;
}

/**
 * DTO for incoming generate campaign requests.
 */
export interface GenerateCampaignDto {
  url: string;
}

/**
 * Response returned by POST /api/campaign/analyze-text.
 */
export interface AnalyzeTextResponse {
  success: boolean;
  productId: string;
  product: ScrapedProduct;
  marketing: MarketingData;
  productData?: ScrapedProduct;
  aiTextContext?: MarketingData;
  timestamp: string;
  message?: string;
}

/**
 * Response returned by POST /api/campaign/generate-media.
 */
export interface GenerateMediaResponse {
  success: boolean;
  productId: string;
  media: MediaAssets;
  timestamp: string;
  message?: string;
}

/**
 * Unified response payload returned to the frontend.
 */
export interface CampaignResponse {
  success: boolean;
  productId: string;
  product: ScrapedProduct;
  marketing: MarketingData;
  media: MediaAssets;
  timestamp: string;
  message?: string;
}
