/**
 * Interface representing the product details scraped from AliExpress.
 */
export interface ScrapedProduct {
  productId: string;
  title: string;
  description: string;
  price: string;
  imageUrls: string[];
  sourceUrl: string;
}

/**
 * Interface representing marketing copy and target audience generated by Google Gemini.
 */
export interface MarketingData {
  facebookAdCopies: string[];
  targetAudience: string[];
  keywords: string[];
}

/**
 * Interface representing local file paths and browser-accessible URLs for media assets.
 */
export interface MediaAssets {
  images: string[];
  videoUrl: string;
  localImagePaths: string[];
  localVideoPath: string;
}

/**
 * DTO for incoming generate campaign requests.
 */
export interface GenerateCampaignDto {
  url: string;
}

/**
 * Unified response payload returned to the frontend.
 */
export interface CampaignResponse {
  success: boolean;
  productId: string;
  product: ScrapedProduct;
  marketing: MarketingData;
  media: MediaAssets;
  timestamp: string;
  message?: string;
}
